with open("db.py", "w") as f:
    f.write('"""\n')
    f.write("MySQL module, to be shared by all modules.\n")
    f.write('"""\n')
    f.write("from mysql.connector import Error, connect\n\n\n")
    f.write("def dbdata(query, data, answers=None):\n")
    f.write('    """\n')
    f.write("    Collects list of posts on the db.\n")
    f.write("    We'll use this function as a template,\n")
    f.write("    letting the functions that call on it\n")
    f.write("    to define its structure. That being\n")
    f.write("    the query and if using .fetchall()\n")
    f.write("    or .commit()\n")
    f.write("    This permits writing just one db function\n")
    f.write("    per module.\n")
    f.write('    """\n')
    f.write("    try:\n")
    f.write("        conn = connect(\n")
    f.write("            host='localhost',\n")
    f.write("            user='mic',\n")
    f.write("            password='xxxx',\n")
    f.write("            database='##### PUT YOUR DATABSE HERE #####',\n")
    f.write("        )\n")
    f.write("        cur = conn.cursor()\n")
    f.write("        if answers:\n")
    f.write("            cur.execute(query, answers)\n")
    f.write("        else:\n")
    f.write("            cur.execute(query)\n")
    f.write("        if data == 'fetch':\n")
    f.write("            data = cur.fetchall()\n")
    f.write("        if data == 'commit':\n")
    f.write("            data = conn.commit()\n")
    f.write("    except Error as e:\n")
    f.write("        print('Error while connecting to db', e)\n")
    f.write("    finally:\n")
    f.write("        if conn:\n")
    f.write("            conn.close()\n\n")
    f.write("    return data")
